name: release

on:
  push:
    tags: ['v*']

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a # v21

      - run: nix flake check -L --accept-flake-config

  tag:
    needs: check
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - run: git push origin "${{ github.ref_name }}:latest" --force

  package:
    needs: check
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a # v21

      - uses: nicknovitski/nix-develop@9be7cfb4b10451d3390a75dc18ad0465bed4932a # v1.2.1
        with:
          arguments: '--accept-flake-config'

      - name: Build & push images
        run: |
          nix build .#image --accept-flake-config

          TAG=${{ github.ref_name }}
          VERSION=${TAG#v}

          ./result | gzip --fast | skopeo copy \
            --dest-creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            docker-archive:/dev/stdin \
            docker://ghcr.io/spotdemo4/discord-openrouter:$VERSION